USE grc_ems;

CREATE TABLE IF NOT EXISTS user_profiles(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED UNIQUE NOT NULL,first_name VARCHAR(100) NOT NULL,middle_name VARCHAR(100),last_name VARCHAR(100) NOT NULL,birth_date DATE,contact_number VARCHAR(30),present_address TEXT,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(user_id)REFERENCES users(id)ON DELETE CASCADE)ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS teacher_sections(teacher_user_id BIGINT UNSIGNED NOT NULL,section_id INT UNSIGNED NOT NULL,assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(teacher_user_id,section_id),FOREIGN KEY(teacher_user_id)REFERENCES users(id)ON DELETE CASCADE,FOREIGN KEY(section_id)REFERENCES sections(id)ON DELETE CASCADE)ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS payment_requests(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,assessment_id BIGINT UNSIGNED NOT NULL,student_profile_id BIGINT UNSIGNED NOT NULL,amount DECIMAL(12,2) NOT NULL,payment_method VARCHAR(80) NOT NULL,payment_reference VARCHAR(100) NOT NULL,receipt_stored_name VARCHAR(255),receipt_original_name VARCHAR(255),receipt_mime_type VARCHAR(100),receipt_file_size INT UNSIGNED,status ENUM('pending','approved','rejected') DEFAULT 'pending',processor_notes TEXT,processed_by BIGINT UNSIGNED,processed_at DATETIME,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(assessment_id)REFERENCES assessments(id)ON DELETE CASCADE,FOREIGN KEY(student_profile_id)REFERENCES student_profiles(id)ON DELETE CASCADE,FOREIGN KEY(processed_by)REFERENCES users(id)ON DELETE SET NULL,INDEX idx_payment_status(status))ENGINE=InnoDB;

INSERT IGNORE INTO permissions(permission_key,description)VALUES('payments.create','Submit student payment requests'),('profile.manage','Manage own profile');
INSERT IGNORE INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_name='Registrar' AND p.permission_key='finance.manage';
INSERT IGNORE INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_name='Staff' AND p.permission_key='finance.manage';
INSERT IGNORE INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_name='Student' AND p.permission_key='payments.create';
INSERT IGNORE INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_name IN('Admin','Registrar','Staff','Teacher','Student') AND p.permission_key='profile.manage';
