-- CLEAN FULL DATABASE FOR GRC ENROLLMENT MANAGEMENT SYSTEM
-- Importing this file replaces the current grc_ems database and removes unrelated tables.
-- Tables are grouped below for RBAC, admissions, student records, academics,
-- assessment/receipt verification, announcements, audit logs, and Helpdesk.
DROP DATABASE IF EXISTS grc_ems;
CREATE DATABASE grc_ems CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE grc_ems;
SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS email_logs,ticket_messages,tickets,payment_requests,assessment_bills,assessments,teacher_sections,user_profiles,class_schedules,subjects,student_profiles,sections,application_documents,applications,announcements,audit_logs,role_permissions,permissions,programs,users,roles;
SET FOREIGN_KEY_CHECKS=1;
-- RBAC foundation: users are assigned roles; roles are assigned permissions.
CREATE TABLE roles(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,role_name VARCHAR(50) UNIQUE NOT NULL,description VARCHAR(255))ENGINE=InnoDB;
CREATE TABLE permissions(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,permission_key VARCHAR(100) UNIQUE NOT NULL,description VARCHAR(255))ENGINE=InnoDB;
CREATE TABLE role_permissions(role_id INT UNSIGNED NOT NULL,permission_id INT UNSIGNED NOT NULL,PRIMARY KEY(role_id,permission_id),FOREIGN KEY(role_id)REFERENCES roles(id)ON DELETE CASCADE,FOREIGN KEY(permission_id)REFERENCES permissions(id)ON DELETE CASCADE)ENGINE=InnoDB;
CREATE TABLE users(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,username VARCHAR(80) UNIQUE NOT NULL,email VARCHAR(190) UNIQUE NOT NULL,password_hash VARCHAR(255) NOT NULL,role_id INT UNSIGNED NOT NULL,status ENUM('active','inactive','locked') DEFAULT 'active',must_change_password BOOLEAN DEFAULT 0,failed_login_attempts TINYINT UNSIGNED DEFAULT 0,last_login_at DATETIME,email_verified_at DATETIME,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(role_id)REFERENCES roles(id),INDEX idx_users_email(email))ENGINE=InnoDB;
CREATE TABLE user_profiles(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED UNIQUE NOT NULL,first_name VARCHAR(100) NOT NULL,middle_name VARCHAR(100),last_name VARCHAR(100) NOT NULL,birth_date DATE,contact_number VARCHAR(30),present_address TEXT,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(user_id)REFERENCES users(id)ON DELETE CASCADE)ENGINE=InnoDB;
CREATE TABLE programs(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,program_code VARCHAR(30) UNIQUE NOT NULL,program_name VARCHAR(190) NOT NULL,department VARCHAR(190),description TEXT,is_active BOOLEAN DEFAULT 1)ENGINE=InnoDB;
-- Admissions: reference_id is given to the applicant; submission_token avoids duplicate form submits.
CREATE TABLE applications(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,reference_id VARCHAR(40) UNIQUE NOT NULL,submission_token CHAR(64) UNIQUE,email VARCHAR(190) NOT NULL,first_name VARCHAR(100) NOT NULL,middle_name VARCHAR(100),last_name VARCHAR(100) NOT NULL,birth_date DATE,contact_number VARCHAR(30),present_address TEXT,last_school_attended VARCHAR(190),lrn VARCHAR(80),strand VARCHAR(150),year_graduated YEAR,enrollment_type ENUM('new','transferee','returning','continuing') DEFAULT 'new',program_id INT UNSIGNED,status ENUM('draft','submitted','under_review','action_required','approved','rejected') DEFAULT 'draft',privacy_consent BOOLEAN DEFAULT 0,review_notes TEXT,reviewed_by BIGINT UNSIGNED,submitted_at DATETIME,reviewed_at DATETIME,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(program_id)REFERENCES programs(id),FOREIGN KEY(reviewed_by)REFERENCES users(id)ON DELETE SET NULL,INDEX idx_app_status(status),INDEX idx_app_email(email))ENGINE=InnoDB;
CREATE TABLE application_documents(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,application_id BIGINT UNSIGNED NOT NULL,document_type VARCHAR(80) NOT NULL,stored_name VARCHAR(255) NOT NULL,original_name VARCHAR(255) NOT NULL,mime_type VARCHAR(100) NOT NULL,file_size INT UNSIGNED NOT NULL,validation_status ENUM('pending','valid','invalid') DEFAULT 'pending',validation_note TEXT,uploaded_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(application_id)REFERENCES applications(id)ON DELETE CASCADE,UNIQUE KEY uq_app_doc(application_id,document_type))ENGINE=InnoDB;
CREATE TABLE sections(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,section_name VARCHAR(80) UNIQUE NOT NULL,program_id INT UNSIGNED NOT NULL,year_level TINYINT UNSIGNED NOT NULL,school_year VARCHAR(20) NOT NULL,semester VARCHAR(20) NOT NULL,capacity SMALLINT UNSIGNED DEFAULT 40,FOREIGN KEY(program_id)REFERENCES programs(id))ENGINE=InnoDB;
CREATE TABLE student_profiles(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED UNIQUE NOT NULL,application_id BIGINT UNSIGNED UNIQUE NOT NULL,student_number VARCHAR(40) UNIQUE NOT NULL,program_id INT UNSIGNED NOT NULL,section_id INT UNSIGNED,is_active BOOLEAN DEFAULT 1,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id)REFERENCES users(id)ON DELETE CASCADE,FOREIGN KEY(application_id)REFERENCES applications(id),FOREIGN KEY(program_id)REFERENCES programs(id),FOREIGN KEY(section_id)REFERENCES sections(id)ON DELETE SET NULL)ENGINE=InnoDB;
CREATE TABLE subjects(id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,subject_code VARCHAR(30) UNIQUE NOT NULL,subject_name VARCHAR(190) NOT NULL,units DECIMAL(3,1) DEFAULT 3.0,program_id INT UNSIGNED,year_level TINYINT UNSIGNED,semester VARCHAR(20),FOREIGN KEY(program_id)REFERENCES programs(id))ENGINE=InnoDB;
CREATE TABLE class_schedules(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,section_id INT UNSIGNED NOT NULL,subject_id INT UNSIGNED NOT NULL,teacher_user_id BIGINT UNSIGNED,day_of_week ENUM('Monday','Tuesday','Wednesday','Thursday','Friday','Saturday') NOT NULL,start_time TIME NOT NULL,end_time TIME NOT NULL,room VARCHAR(80),instructor VARCHAR(190),FOREIGN KEY(section_id)REFERENCES sections(id)ON DELETE CASCADE,FOREIGN KEY(subject_id)REFERENCES subjects(id),FOREIGN KEY(teacher_user_id)REFERENCES users(id)ON DELETE SET NULL,INDEX idx_schedule_teacher(teacher_user_id))ENGINE=InnoDB;
CREATE TABLE teacher_sections(teacher_user_id BIGINT UNSIGNED NOT NULL,section_id INT UNSIGNED NOT NULL,assigned_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,PRIMARY KEY(teacher_user_id,section_id),FOREIGN KEY(teacher_user_id)REFERENCES users(id)ON DELETE CASCADE,FOREIGN KEY(section_id)REFERENCES sections(id)ON DELETE CASCADE)ENGINE=InnoDB;
CREATE TABLE assessments(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,student_profile_id BIGINT UNSIGNED NOT NULL,description VARCHAR(190) NOT NULL,amount DECIMAL(12,2) NOT NULL,amount_paid DECIMAL(12,2) NOT NULL DEFAULT 0.00,due_date DATE,school_year VARCHAR(20),semester VARCHAR(20),created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(student_profile_id)REFERENCES student_profiles(id)ON DELETE CASCADE,INDEX idx_assessment_student(student_profile_id))ENGINE=InnoDB;
-- Detailed charges belong to one assessment. Active bill totals update the parent assessment.
CREATE TABLE assessment_bills(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,assessment_id BIGINT UNSIGNED NOT NULL,bill_code VARCHAR(40) NOT NULL,bill_name VARCHAR(190) NOT NULL,amount DECIMAL(12,2) NOT NULL,due_date DATE,notes TEXT,is_active BOOLEAN NOT NULL DEFAULT 1,created_by BIGINT UNSIGNED,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(assessment_id)REFERENCES assessments(id)ON DELETE CASCADE,FOREIGN KEY(created_by)REFERENCES users(id)ON DELETE SET NULL,UNIQUE KEY uq_assessment_bill_code(assessment_id,bill_code),INDEX idx_bill_assessment(assessment_id))ENGINE=InnoDB;
CREATE TABLE payment_requests(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,assessment_id BIGINT UNSIGNED NOT NULL,student_profile_id BIGINT UNSIGNED NOT NULL,amount DECIMAL(12,2) NOT NULL,payment_method VARCHAR(80) NOT NULL,payment_reference VARCHAR(100) NOT NULL,receipt_stored_name VARCHAR(255),receipt_original_name VARCHAR(255),receipt_mime_type VARCHAR(100),receipt_file_size INT UNSIGNED,status ENUM('pending','approved','rejected') DEFAULT 'pending',processor_notes TEXT,processed_by BIGINT UNSIGNED,processed_at DATETIME,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(assessment_id)REFERENCES assessments(id)ON DELETE CASCADE,FOREIGN KEY(student_profile_id)REFERENCES student_profiles(id)ON DELETE CASCADE,FOREIGN KEY(processed_by)REFERENCES users(id)ON DELETE SET NULL,INDEX idx_payment_status(status))ENGINE=InnoDB;
CREATE TABLE announcements(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,title VARCHAR(190) NOT NULL,body TEXT NOT NULL,audience ENUM('all','students','staff') DEFAULT 'all',is_published BOOLEAN DEFAULT 1,published_by BIGINT UNSIGNED,published_at DATETIME,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(published_by)REFERENCES users(id)ON DELETE SET NULL)ENGINE=InnoDB;
CREATE TABLE tickets(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,ticket_number VARCHAR(40) UNIQUE NOT NULL,student_user_id BIGINT UNSIGNED NOT NULL,category VARCHAR(80) NOT NULL,subject VARCHAR(190) NOT NULL,status ENUM('open','in_progress','resolved','closed') DEFAULT 'open',priority ENUM('low','normal','high','urgent') DEFAULT 'normal',assigned_to BIGINT UNSIGNED,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,FOREIGN KEY(student_user_id)REFERENCES users(id),FOREIGN KEY(assigned_to)REFERENCES users(id)ON DELETE SET NULL,INDEX idx_ticket_status(status))ENGINE=InnoDB;
CREATE TABLE ticket_messages(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,ticket_id BIGINT UNSIGNED NOT NULL,sender_user_id BIGINT UNSIGNED NOT NULL,message TEXT NOT NULL,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(ticket_id)REFERENCES tickets(id)ON DELETE CASCADE,FOREIGN KEY(sender_user_id)REFERENCES users(id))ENGINE=InnoDB;
CREATE TABLE email_logs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,recipient VARCHAR(190) NOT NULL,subject VARCHAR(190) NOT NULL,body MEDIUMTEXT NOT NULL,status ENUM('sent','failed') NOT NULL,error_message TEXT,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,INDEX idx_email_status(status))ENGINE=InnoDB;
CREATE TABLE audit_logs(id BIGINT UNSIGNED AUTO_INCREMENT PRIMARY KEY,user_id BIGINT UNSIGNED,action VARCHAR(120) NOT NULL,target_table VARCHAR(80),target_id BIGINT UNSIGNED,ip_address VARCHAR(45),user_agent VARCHAR(255),details_json JSON,created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,FOREIGN KEY(user_id)REFERENCES users(id)ON DELETE SET NULL,INDEX idx_audit_created(created_at))ENGINE=InnoDB;
INSERT INTO roles(id,role_name,description)VALUES(1,'Super Admin','All permissions'),(2,'Admin','Enrollment and campus operations'),(3,'Registrar','Admissions and records'),(4,'Staff','Limited application and helpdesk processing'),(5,'Student','Student portal access'),(6,'Teacher','Teaching staff access');
INSERT INTO permissions(permission_key,description)VALUES('applications.view','View submitted applications'),('applications.review','Process applications'),('students.view','View student records'),('students.manage','Manage student records'),('users.manage','Manage staff and administrator accounts'),('academics.manage','Manage programs, sections, subjects, and schedules'),('finance.manage','Manage assessments and verify payments'),('payments.create','Submit student payment requests'),('announcements.manage','Publish announcements'),('tickets.manage','Manage helpdesk tickets'),('tickets.create','Create helpdesk tickets'),('tickets.view','View permitted tickets'),('reports.view','View reports'),('portal.view','Use student portal'),('profile.manage','Manage own profile');
INSERT INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_name='Admin' AND p.permission_key IN('applications.view','applications.review','students.view','students.manage','academics.manage','finance.manage','announcements.manage','tickets.manage','tickets.view','reports.view');
INSERT INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_name='Admin' AND p.permission_key='users.manage';
INSERT INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_name='Registrar' AND p.permission_key IN('applications.view','applications.review','students.view','students.manage','academics.manage','finance.manage','announcements.manage','tickets.manage','tickets.view','reports.view');
INSERT INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_name='Staff' AND p.permission_key='finance.manage';
INSERT INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_name='Staff' AND p.permission_key IN('applications.view','applications.review','students.view','tickets.manage','tickets.view');
INSERT INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_name='Teacher' AND p.permission_key IN('tickets.manage','tickets.view','profile.manage');
INSERT INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_name='Student' AND p.permission_key IN('portal.view','tickets.create','tickets.view','profile.manage','payments.create');
INSERT INTO role_permissions(role_id,permission_id)SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.role_name IN('Admin','Registrar','Staff') AND p.permission_key='profile.manage';
INSERT INTO programs(id,program_code,program_name,department,description,is_active)VALUES(1,'BSIT','Bachelor of Science in Information Technology','Computer Studies','Software, networks, data, and information systems.',1),(2,'BSBA','Bachelor of Science in Business Administration','Business','Management, marketing, finance, and enterprise.',1),(3,'BSHM','Bachelor of Science in Hospitality Management','Hospitality','Hospitality operations and service management.',1),(4,'BSEd','Bachelor of Secondary Education','Education','Professional preparation for secondary teaching.',1),(5,'BSA','Bachelor of Science in Accountancy','Business','Accounting, auditing, taxation, and finance.',1);

-- Compatible account records retained from the uploaded EMS dump.
INSERT INTO users(id,username,email,password_hash,role_id,status,must_change_password,failed_login_attempts,last_login_at,email_verified_at,created_at,updated_at)VALUES
(1,'admin','admin@gmail.com','$2y$10$92IXUNpkjO0rOQ5byMi.Ye4oKoEa3Ro9llC/.og/at2uheWG/igi.',1,'active',0,0,NULL,'2026-09-05 13:34:12','2026-09-05 05:34:12','2026-09-05 05:34:12'),
(2,'ADMINISTRATOR','sp@gmail.com','$2y$10$g3LlbZ3WSNgn21wOnCCtaOrqa5wwrB6.hGHrRrrlY39DP1Xk4.njK',1,'active',0,0,'2026-09-09 00:46:35','2026-09-05 13:46:42','2026-09-05 05:46:42','2026-09-08 16:46:35'),
(3,'student2600001','siijaayy5@gmail.com','$2y$10$4pKkBgLdjMmTkbwIYuyYA.R3MSKoGhsqSavbwXnTCrE0wcHGHWobW',5,'active',0,0,'2026-09-09 00:45:20','2026-09-05 13:49:08','2026-09-05 05:49:08','2026-09-08 16:45:20'),
(4,'creasan','1@gmail.com','$2y$10$FT7EjUinYRwvf0hAQiIuYO3LEWDVEWpA.7TLaK38pp/L5KfSRROr.',3,'active',0,0,'2026-09-06 15:52:25','2026-09-06 11:45:04','2026-09-06 03:45:04','2026-09-06 07:52:25'),
(5,'student2600002','aibandrosalviolon@gmail.com','$2y$10$uABtdsQFbp3/ICw808JiPeD.eOKKM42BeXrcQx7HjtC91OMx3jVnS',5,'active',1,0,NULL,'2026-09-06 15:18:56','2026-09-06 07:18:56','2026-09-06 07:18:56');

INSERT INTO applications(id,reference_id,submission_token,email,first_name,middle_name,last_name,birth_date,contact_number,present_address,last_school_attended,lrn,strand,year_graduated,enrollment_type,program_id,status,privacy_consent,review_notes,reviewed_by,submitted_at,reviewed_at,created_at,updated_at)VALUES
(1,'GRC-APP-26-6BFE65','5548e7a5-3049-40b4-a0bf-8ed07a5fdf2a','siijaayy5@gmail.com','Creasan Jade','Cacal','Vidad','2026-09-01','09123456678','kaingin','bcp','21312841829','ICT',NULL,'new',1,'approved',1,NULL,2,'2026-09-05 13:48:31','2026-09-06 11:06:24','2026-09-05 05:48:31','2026-09-06 03:06:24'),
(2,'GRC-APP-26-A36779','667b4bdd-452a-4368-94cd-b55ac5bfc084','aibandrosalviolon@gmail.com','Aiband','Rosal','Violon','2005-06-13','09055286050','weweweweawrawr','Arellano Elisa Esguerra Campus','136839090559','HUMSS','2023','new',1,'approved',1,NULL,2,'2026-09-06 15:14:47','2026-09-06 15:18:56','2026-09-06 07:14:47','2026-09-06 07:18:56');

INSERT INTO application_documents(id,application_id,document_type,stored_name,original_name,mime_type,file_size,validation_status,validation_note,uploaded_at)VALUES
(1,2,'birth_certificate','b1dc1090f593f0ec6f28371cf7651466.jpg','images (4).jpg','image/jpeg',37438,'pending',NULL,'2026-09-06 07:14:47'),
(2,2,'academic_record','25747656a155762fe20a17eb031e293f.jpg','images (4).jpg','image/jpeg',37438,'pending',NULL,'2026-09-06 07:14:47'),
(3,2,'id_photo','8c844b921e0762a50d8f7bab9b04f7a9.jpg','images (4).jpg','image/jpeg',37438,'pending',NULL,'2026-09-06 07:14:47'),
(4,2,'good_moral','48ba030a475526fa0d53416eb9d3600e.jpg','images (4).jpg','image/jpeg',37438,'pending',NULL,'2026-09-06 07:14:47');

INSERT INTO sections(id,section_name,program_id,year_level,school_year,semester,capacity)VALUES(2,'BSIT - 123',1,1,'2026-2027','1st',50);
INSERT INTO student_profiles(id,user_id,application_id,student_number,program_id,section_id,is_active,created_at)VALUES(1,3,1,'GRC-2026-00003',1,2,1,'2026-09-05 05:49:08'),(2,5,2,'GRC-2026-00005',1,2,1,'2026-09-06 07:18:56');
INSERT INTO subjects(id,subject_code,subject_name,units,program_id,year_level,semester)VALUES(3,'PM','Project Management',8.0,1,1,'1st');
INSERT INTO assessments(id,student_profile_id,description,amount,amount_paid,due_date,school_year,semester,created_at,updated_at)VALUES(1,1,'Tuition and miscellaneous fees',18500.00,18000.00,'2026-10-05','2026-2027','1st','2026-09-05 05:49:08','2026-09-06 05:45:13'),(2,2,'Tuition fee',15000.00,0.00,'2026-10-06','2026-2027','1st','2026-09-06 07:18:56','2026-09-06 07:18:56'),(3,2,'Miscellaneous fees',3500.00,0.00,'2026-10-06','2026-2027','1st','2026-09-06 07:18:56','2026-09-06 07:18:56');
INSERT INTO announcements(id,title,body,audience,is_published,published_by,published_at,created_at)VALUES(1,'Enrollment for First Semester is open','Submit complete requirements before the published deadline.','all',1,NULL,'2026-09-05 13:34:12','2026-09-05 05:34:12'),(2,'Student orientation','New-student orientation will be held at the main auditorium.','students',1,NULL,'2026-09-05 13:34:12','2026-09-05 05:34:12');
INSERT INTO email_logs(id,recipient,subject,body,status,error_message,created_at)VALUES(1,'siijaayy5@gmail.com','GRC Application Approved – Your Student Portal Account','[Credential email redacted] Application GRC-APP-26-6BFE65 approved; account GRC-2026-00003 created.','sent',NULL,'2026-09-05 05:49:12'),(4,'aibandrosalviolon@gmail.com','GRC Application Approved – Your Student Portal Account','[Credential email redacted] Application GRC-APP-26-A36779 approved; account GRC-2026-00005 created.','sent',NULL,'2026-09-06 07:19:01');

-- Reset counters above retained IDs so new records continue safely.
ALTER TABLE users AUTO_INCREMENT=6;
ALTER TABLE applications AUTO_INCREMENT=3;
ALTER TABLE application_documents AUTO_INCREMENT=5;
ALTER TABLE sections AUTO_INCREMENT=3;
ALTER TABLE student_profiles AUTO_INCREMENT=3;
ALTER TABLE subjects AUTO_INCREMENT=4;
ALTER TABLE class_schedules AUTO_INCREMENT=4;
ALTER TABLE assessments AUTO_INCREMENT=4;
ALTER TABLE announcements AUTO_INCREMENT=3;
ALTER TABLE email_logs AUTO_INCREMENT=5;
