<?php
declare(strict_types=1);
// Main JSON API gateway. Frontend pages call api.php?action=<route>.
// This file validates requests, uses database helpers, and returns JSON responses.
ini_set('display_errors','0');
require __DIR__.'/config.php';
// Read the route from the URL and request data from JSON or a regular form submission.
$action=$_GET['action']??''; $method=$_SERVER['REQUEST_METHOD']; $json=json_decode(file_get_contents('php://input'),true)?:$_POST;
try {
 // Session and authentication routes.
 if($action==='csrf'){respond(['success'=>true,'data'=>['token'=>$_SESSION['csrf']]]);}
 if($action==='session'){$u=require_auth();respond(['success'=>true,'data'=>['user'=>$u,'csrf'=>$_SESSION['csrf']]]);}
 if($action==='login'&&$method==='POST'){csrf_check();$stmt=db()->prepare('SELECT u.id,u.email,u.password_hash,u.status,u.must_change_password,r.role_name FROM users u JOIN roles r ON r.id=u.role_id WHERE u.email=? LIMIT 1');$stmt->execute([strtolower(trim($json['email']??''))]);$x=$stmt->fetch();if(!$x||$x['status']!=='active'||!password_verify($json['password']??'',$x['password_hash']))respond(['success'=>false,'error'=>'Invalid email or password.'],422);session_regenerate_id(true);$_SESSION['user']=['id'=>(int)$x['id'],'email'=>$x['email'],'role_name'=>$x['role_name'],'must_change_password'=>(bool)$x['must_change_password']];db()->prepare('UPDATE users SET last_login_at=NOW(),failed_login_attempts=0 WHERE id=?')->execute([$x['id']]);audit('auth.login','users',(int)$x['id']);respond(['success'=>true,'data'=>$_SESSION['user']]);}
 if($action==='logout'&&$method==='POST'){require_auth();csrf_check();audit('auth.logout');$_SESSION=[];session_destroy();respond(['success'=>true]);}
 // Management CRUD is separated into its own controller for cleaner organization.
 require_once __DIR__.'/api/controllers/management.php';
 handle_management_request($action,$method,$json);
 if($action==='account_create'&&$method==='POST'){
  if(!is_file(__DIR__.'/create_account.html'))respond(['success'=>false,'error'=>'The temporary account creator has been disabled.'],404);
  csrf_check();
  $username=trim((string)($json['username']??''));$email=strtolower(trim((string)($json['email']??'')));$password=(string)($json['password']??'');$roleName=trim((string)($json['role_name']??''));$mustChange=!empty($json['must_change_password'])?1:0;
  $allowedRoles=['Super Admin','Admin','Registrar','Staff','Teacher','Student'];
  if(!preg_match('/^[A-Za-z0-9._-]{3,80}$/',$username))respond(['success'=>false,'error'=>'Username must be 3–80 characters and use only letters, numbers, dots, underscores, or hyphens.'],422);
  if(!filter_var($email,FILTER_VALIDATE_EMAIL)||strlen($email)>190)respond(['success'=>false,'error'=>'Enter a valid email address.'],422);
  if(strlen($password)<8||strlen($password)>128)respond(['success'=>false,'error'=>'Password must contain 8–128 characters.'],422);
  if(!in_array($roleName,$allowedRoles,true))respond(['success'=>false,'error'=>'Select a valid account role.'],422);
  $pdo=db();$q=$pdo->prepare('SELECT id FROM roles WHERE role_name=? LIMIT 1');$q->execute([$roleName]);$roleId=$q->fetchColumn();if(!$roleId)respond(['success'=>false,'error'=>'The selected role does not exist in the database. Import the latest SQL first.'],422);
  $hash=password_hash($password,PASSWORD_DEFAULT);if($hash===false)throw new RuntimeException('Password hashing failed.');
  $q=$pdo->prepare("INSERT INTO users(username,email,password_hash,role_id,status,must_change_password,email_verified_at) VALUES(?,?,?,?,'active',?,NOW())");$q->execute([$username,$email,$hash,(int)$roleId,$mustChange]);$id=(int)$pdo->lastInsertId();
  audit('account.manual_create','users',$id,['role'=>$roleName,'temporary_setup_page'=>true]);respond(['success'=>true,'data'=>['id'=>$id,'username'=>$username,'email'=>$email,'role_name'=>$roleName]]);
 }
 // Public list used to fill the Program dropdown on the application form.
 if($action==='programs'){respond(['success'=>true,'data'=>db()->query('SELECT id,program_code,program_name,department,description FROM programs WHERE is_active=1 ORDER BY program_name')->fetchAll()]);}
 // Admissions-only application details and secure document viewer.
 if($action==='application_detail'){
  require_permission('applications.view');$id=(int)($_GET['id']??0);$pdo=db();
  $q=$pdo->prepare("SELECT a.*,p.program_code,p.program_name,CONCAT_WS(' ',reviewer.username,reviewer.email) reviewer_name FROM applications a LEFT JOIN programs p ON p.id=a.program_id LEFT JOIN users reviewer ON reviewer.id=a.reviewed_by WHERE a.id=? AND a.status!='draft'");$q->execute([$id]);$application=$q->fetch();
  if(!$application)respond(['success'=>false,'error'=>'Application not found.'],404);
  $q=$pdo->prepare('SELECT id,document_type,original_name,mime_type,file_size,validation_status,validation_note,uploaded_at FROM application_documents WHERE application_id=? ORDER BY document_type');$q->execute([$id]);
  respond(['success'=>true,'data'=>['application'=>$application,'documents'=>$q->fetchAll()]]);
 }
 if($action==='application_document'){
  require_permission('applications.view');$id=(int)($_GET['id']??0);$q=db()->prepare('SELECT d.* FROM application_documents d JOIN applications a ON a.id=d.application_id WHERE d.id=? AND a.status!=\'draft\'');$q->execute([$id]);$document=$q->fetch();
  if(!$document)respond(['success'=>false,'error'=>'Document not found.'],404);
  $path=__DIR__.'/storage/private_uploads/'.basename($document['stored_name']);if(!is_file($path))respond(['success'=>false,'error'=>'The uploaded file is unavailable.'],404);
  header('Content-Type: '.$document['mime_type']);header('Content-Length: '.filesize($path));header("Content-Disposition: inline; filename*=UTF-8''".rawurlencode($document['original_name']));header('X-Content-Type-Options: nosniff');readfile($path);exit;
 }
 if($action==='application_resume'){$stmt=db()->prepare('SELECT * FROM applications WHERE reference_id=? AND email=? AND status IN (\'draft\',\'action_required\')');$stmt->execute([$_GET['reference']??'',strtolower(trim($_GET['email']??''))]);$x=$stmt->fetch();if(!$x)respond(['success'=>false,'error'=>'Draft not found. Check the reference ID and email.'],404);respond(['success'=>true,'data'=>['application'=>$x]]);}
 if($action==='application_delete'&&$method==='POST'){$staff=require_permission('applications.review');csrf_check();$id=(int)($json['id']??0);$pdo=db();$q=$pdo->prepare('SELECT reference_id,status FROM applications WHERE id=?');$q->execute([$id]);$record=$q->fetch();if(!$record)respond(['success'=>false,'error'=>'Application not found.'],404);if($record['status']==='approved')respond(['success'=>false,'error'=>'Approved applications are linked to student profiles. Delete the student from Student Profiling instead.'],409);$q=$pdo->prepare('SELECT stored_name FROM application_documents WHERE application_id=?');$q->execute([$id]);$files=$q->fetchAll(PDO::FETCH_COLUMN);$pdo->prepare('DELETE FROM applications WHERE id=?')->execute([$id]);foreach($files as $file){$path=__DIR__.'/storage/private_uploads/'.basename((string)$file);if(is_file($path))@unlink($path);}audit('application.delete','applications',$id,['reference_id'=>$record['reference_id'],'deleted_by'=>$staff['id']]);respond(['success'=>true,'data'=>['deleted'=>true]]);}
 // Online application workflow: validate input, prevent duplicates, store files privately,
 // then return the saved application's Reference ID.
 if($action==='application_save'&&$method==='POST'){
  csrf_check();
  foreach(['first_name','last_name','email'] as $f)if(empty($_POST[$f]))respond(['success'=>false,'error'=>"Missing required field: $f"],422);
  $token=trim((string)($_POST['submission_token']??''));if(!preg_match('/^[A-Za-z0-9-]{20,64}$/',$token))respond(['success'=>false,'error'=>'Invalid submission session. Refresh the page and try again.'],422);
  $email=strtolower(trim($_POST['email']));$ref=trim($_POST['reference_id']??'')?:reference_id();$mode=$_POST['mode']??'draft';$status=$mode==='submit'?'submitted':'draft';$pdo=db();
  $stmt=$pdo->prepare('SELECT reference_id,status FROM applications WHERE submission_token=? LIMIT 1');$stmt->execute([$token]);if($same=$stmt->fetch())respond(['success'=>true,'data'=>['reference_id'=>$same['reference_id'],'status'=>$same['status'],'duplicate'=>true]]);
  if($status==='submitted'){$stmt=$pdo->prepare("SELECT reference_id,status FROM applications WHERE email=? AND status IN ('submitted','under_review','action_required','approved') ORDER BY id DESC LIMIT 1");$stmt->execute([$email]);if($existing=$stmt->fetch())respond(['success'=>true,'data'=>['reference_id'=>$existing['reference_id'],'status'=>$existing['status'],'duplicate'=>true]]);}
  $stmt=$pdo->prepare("INSERT INTO applications(reference_id,submission_token,email,first_name,middle_name,last_name,birth_date,contact_number,present_address,last_school_attended,lrn,strand,year_graduated,enrollment_type,program_id,status,privacy_consent,submitted_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,IF(?='submitted',NOW(),NULL)) ON DUPLICATE KEY UPDATE submission_token=VALUES(submission_token)");
  $stmt->execute([$ref,$token,$email,$_POST['first_name'],$_POST['middle_name']??null,$_POST['last_name'],$_POST['birth_date']?:null,$_POST['contact_number']??null,$_POST['present_address']??null,$_POST['last_school_attended']??null,$_POST['lrn']??null,$_POST['strand']??null,$_POST['year_graduated']?:null,$_POST['enrollment_type']??'new',($_POST['program_id']??'')?:null,$status,(int)($_POST['privacy_consent']??0),$status]);
  $stmt=$pdo->prepare('SELECT id,reference_id FROM applications WHERE submission_token=?');$stmt->execute([$token]);$saved=$stmt->fetch();if(!$saved)throw new RuntimeException('The application could not be saved.');$id=(int)$saved['id'];$ref=$saved['reference_id'];
  foreach(['birth_certificate','academic_record','id_photo','good_moral'] as $type)if(isset($_FILES[$type])&&$_FILES[$type]['error']!==UPLOAD_ERR_NO_FILE){$f=$_FILES[$type];if($f['error']!==UPLOAD_ERR_OK||$f['size']>($config['max_upload_bytes']??5242880))respond(['success'=>false,'error'=>"Invalid or oversized file: $type"],422);$mime=(new finfo(FILEINFO_MIME_TYPE))->file($f['tmp_name']);if(!in_array($mime,['application/pdf','image/jpeg'],true))respond(['success'=>false,'error'=>'Only PDF and JPEG files are accepted.'],422);$ext=$mime==='application/pdf'?'pdf':'jpg';$name=bin2hex(random_bytes(16)).'.'.$ext;$dir=__DIR__.'/storage/private_uploads';if(!is_dir($dir))mkdir($dir,0750,true);if(!move_uploaded_file($f['tmp_name'],$dir.'/'.$name))throw new RuntimeException('File storage failed');$q=$pdo->prepare('INSERT INTO application_documents(application_id,document_type,stored_name,original_name,mime_type,file_size) VALUES(?,?,?,?,?,?) ON DUPLICATE KEY UPDATE stored_name=VALUES(stored_name),original_name=VALUES(original_name),mime_type=VALUES(mime_type),file_size=VALUES(file_size),validation_status=\'pending\'');$q->execute([$id,$type,$name,$f['name'],$mime,$f['size']]);}
  respond(['success'=>true,'data'=>['reference_id'=>$ref,'status'=>$status]]);
 }
 // First-login password change: store only the password hash and clear the required flag.
 if($action==='password_change'&&$method==='POST'){$u=require_auth();csrf_check();$pw=(string)($json['password']??'');if(strlen($pw)<8)respond(['success'=>false,'error'=>'Password must be at least 8 characters.'],422);if(strlen($pw)>128)respond(['success'=>false,'error'=>'Password must not exceed 128 characters.'],422);$hash=password_hash($pw,PASSWORD_DEFAULT);if($hash===false)throw new RuntimeException('Password hashing failed.');$stmt=db()->prepare('UPDATE users SET password_hash=?,must_change_password=0,failed_login_attempts=0 WHERE id=?');$stmt->execute([$hash,$u['id']]);if($stmt->rowCount()<1)respond(['success'=>false,'error'=>'The password was not updated. Please sign in again.'],409);$_SESSION['user']['must_change_password']=false;audit('auth.password_changed','users',$u['id']);respond(['success'=>true,'data'=>['changed'=>true]]);}
 // Dashboard and portal routes return data based on the authenticated user's role.
 if(strncmp($action,'portal',6)===0){$u=require_auth();$view=$_GET['view']??'';$pdo=db();
  if($view==='admin-dashboard'){require_permission('applications.view');$c=['applications'=>(int)$pdo->query("SELECT COUNT(*) FROM applications WHERE status!='draft'")->fetchColumn(),'action_required'=>(int)$pdo->query("SELECT COUNT(*) FROM applications WHERE status='action_required'")->fetchColumn(),'students'=>(int)$pdo->query("SELECT COUNT(*) FROM student_profiles WHERE is_active=1")->fetchColumn(),'tickets'=>(int)$pdo->query("SELECT COUNT(*) FROM tickets WHERE status!='resolved'")->fetchColumn()];respond(['success'=>true,'data'=>['counts'=>$c,'applications'=>applications()]]);}
  if($view==='teacher-dashboard'){require_auth(['Teacher']);respond(['success'=>true,'data'=>$pdo->query("SELECT su.subject_code,su.subject_name,su.units,sc.day_of_week,TIME_FORMAT(sc.start_time,'%h:%i %p') start_time,TIME_FORMAT(sc.end_time,'%h:%i %p') end_time,sc.room,sc.instructor FROM class_schedules sc JOIN subjects su ON su.id=sc.subject_id ORDER BY FIELD(sc.day_of_week,'Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'),sc.start_time")->fetchAll()]);}
  if($view==='applications'){require_permission('applications.view');respond(['success'=>true,'data'=>applications()]);}
  if($view==='students'){require_permission('students.view');respond(['success'=>true,'data'=>$pdo->query("SELECT CONCAT(a.first_name,' ',a.last_name) name,u.email,sp.student_number,p.program_code,se.section_name FROM student_profiles sp JOIN users u ON u.id=sp.user_id JOIN applications a ON a.id=sp.application_id JOIN programs p ON p.id=sp.program_id LEFT JOIN sections se ON se.id=sp.section_id WHERE sp.is_active=1")->fetchAll()]);}
  if($view==='academics'){require_permission('academics.manage');respond(['success'=>true,'data'=>$pdo->query("SELECT su.subject_code,su.subject_name,se.section_name,sc.day_of_week,TIME_FORMAT(sc.start_time,'%h:%i %p') start_time,TIME_FORMAT(sc.end_time,'%h:%i %p') end_time,sc.room FROM class_schedules sc JOIN subjects su ON su.id=sc.subject_id JOIN sections se ON se.id=sc.section_id ORDER BY FIELD(sc.day_of_week,'Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'),sc.start_time")->fetchAll()]);}
  if($view==='announcements'){respond(['success'=>true,'data'=>$pdo->query("SELECT * FROM announcements WHERE is_published=1 AND (audience='all' OR audience='".($u['role_name']==='Student'?'students':'staff')."') ORDER BY published_at DESC")->fetchAll()]);}
  if($view==='helpdesk'){$q=$u['role_name']==='Student'?"SELECT * FROM tickets WHERE student_user_id={$u['id']} ORDER BY updated_at DESC":"SELECT * FROM tickets ORDER BY updated_at DESC";respond(['success'=>true,'data'=>$pdo->query($q)->fetchAll()]);}
  if($u['role_name']==='Student'){$s=student($u['id']);if(!$s)respond(['success'=>false,'error'=>'Student profile is not ready.'],404);if($view==='student-dashboard'){$today=schedule((int)$s['section_id'],date('l'));$anns=$pdo->query("SELECT title,body,published_at FROM announcements WHERE is_published=1 AND audience IN ('all','students') ORDER BY published_at DESC LIMIT 4")->fetchAll();$bal=balance((int)$s['id']);$q=$pdo->prepare("SELECT COUNT(*) FROM tickets WHERE student_user_id=? AND status!='resolved'");$q->execute([$u['id']]);respond(['success'=>true,'data'=>['student'=>$s,'today'=>$today,'announcements'=>$anns,'balance'=>$bal['balance'],'open_tickets'=>(int)$q->fetchColumn()]]);}
   if($view==='profile')respond(['success'=>true,'data'=>['student'=>$s,'schedule'=>schedule((int)$s['section_id'])]]);
   if($view==='schedule')respond(['success'=>true,'data'=>schedule((int)$s['section_id'])]);if($view==='finance')respond(['success'=>true,'data'=>balance((int)$s['id'])]);}
 }
 // Admissions decision workflow. Approval creates the user and student profile in a transaction,
 // then emails credentials. Correction and rejection emails include the staff message.
 if($action==='application_review'&&$method==='POST'){$staff=require_permission('applications.review');csrf_check();$id=(int)($json['id']??0);$status=$json['status']??'';$message=trim((string)($json['message']??''));if(!in_array($status,['action_required','approved','rejected'],true))respond(['success'=>false,'error'=>'Invalid decision.'],422);if($status==='action_required'&&$message==='')respond(['success'=>false,'error'=>'Enter the required corrections before requesting a correction.'],422);$pdo=db();$pdo->beginTransaction();$q=$pdo->prepare('SELECT a.*,p.program_code FROM applications a JOIN programs p ON p.id=a.program_id WHERE a.id=? FOR UPDATE');$q->execute([$id]);$a=$q->fetch();if(!$a){$pdo->rollBack();respond(['success'=>false,'error'=>'Application not found or no program was selected.'],404);}if($status==='approved'){$q=$pdo->prepare("SELECT u.id,r.role_name FROM users u JOIN roles r ON r.id=u.role_id WHERE u.email=? LIMIT 1");$q->execute([$a['email']]);$existing=$q->fetch();if($existing){$pdo->rollBack();respond(['success'=>false,'error'=>$existing['role_name']==='Student'?'A student account already exists for this email. Use a different applicant email or manage the existing student record.':'This email already belongs to a '.$existing['role_name'].' account and cannot be used for a student account.'],409);}}$pdo->prepare('UPDATE applications SET status=?,review_notes=?,reviewed_by=?,reviewed_at=NOW() WHERE id=?')->execute([$status,$message?:null,$staff['id'],$id]);
  if($status==='approved'){
   if($a['status']==='approved')respond(['success'=>false,'error'=>'This application is already approved.'],409);
   $registeredAt=$a['submitted_at']?:$a['created_at'];$registrationYear=$registeredAt?(int)date('Y',strtotime($registeredAt)):(int)date('Y');$pw=temp_password($a['last_name'],$registrationYear);
   $role=(int)$pdo->query("SELECT id FROM roles WHERE role_name='Student'")->fetchColumn();$username='student'.substr((string)$registrationYear,-2).str_pad((string)$id,5,'0',STR_PAD_LEFT);
   $pdo->prepare("INSERT INTO users(username,email,password_hash,role_id,status,must_change_password,email_verified_at) VALUES(?,?,?,?,'active',1,NOW())")->execute([$username,$a['email'],password_hash($pw,PASSWORD_DEFAULT),$role]);$uid=(int)$pdo->lastInsertId();$no='GRC-'.$registrationYear.'-'.str_pad((string)$uid,5,'0',STR_PAD_LEFT);
   $sec=$pdo->prepare('SELECT id FROM sections WHERE program_id=? AND school_year=? ORDER BY id LIMIT 1');$sec->execute([$a['program_id'],'2026-2027']);$section=$sec->fetchColumn()?:null;$pdo->prepare('INSERT INTO student_profiles(user_id,application_id,student_number,program_id,section_id,is_active) VALUES(?,?,?,?,?,1)')->execute([$uid,$id,$no,$a['program_id'],$section]);$profile=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO assessments(student_profile_id,description,amount,amount_paid,due_date,school_year,semester) VALUES(?, 'Tuition fee',15000.00,0.00,DATE_ADD(CURDATE(),INTERVAL 30 DAY),'2026-2027','1st'),(?, 'Miscellaneous fees',3500.00,0.00,DATE_ADD(CURDATE(),INTERVAL 30 DAY),'2026-2027','1st')")->execute([$profile,$profile]);$pdo->commit();
   $name=htmlspecialchars(trim($a['first_name'].' '.$a['last_name']));$email=htmlspecialchars($a['email']);$password=htmlspecialchars($pw);$reference=htmlspecialchars($a['reference_id']);$program=htmlspecialchars($a['program_code']);$studentNo=htmlspecialchars($no);$login=htmlspecialchars(portal_login_url());$additional=$message!==''?'<p><b>Additional instructions from Admissions:</b><br>'.nl2br(htmlspecialchars($message)).'</p>':'';
   $html='<h2>Your GRC application has been approved</h2><p>Dear '.$name.',</p><p>Congratulations! Global Reciprocal Colleges has approved your application. Your student portal account is now ready.</p><p><b>Application reference:</b> '.$reference.'<br><b>Program:</b> '.$program.'<br><b>Student number:</b> '.$studentNo.'</p><h3>Student portal credentials</h3><p><b>Login email:</b> '.$email.'<br><b>Temporary password:</b> '.$password.'<br><b>Portal:</b> <a href="'.$login.'">'.$login.'</a></p>'.$additional.'<p>For your security, the system will require you to create a new password on your first login. Do not share these credentials.</p><p>If you need assistance, contact GRC Admissions or visit the school campus.</p><p>Welcome to Global Reciprocal Colleges.</p>';
   $emailSent=send_system_mail($a['email'],'GRC Application Approved – Your Student Portal Account',$html,'[Credential email redacted] Application '.$a['reference_id'].' approved; account '.$no.' created.');
  } else {
   $pdo->commit();$name=htmlspecialchars(trim($a['first_name'].' '.$a['last_name']));$reference=htmlspecialchars($a['reference_id']);
   if($status==='rejected'){$reason=$message!==''?'<p><b>Review details:</b><br>'.nl2br(htmlspecialchars($message)).'</p>':'<p>The submitted application did not meet the current enrollment requirements.</p>';$phone=htmlspecialchars((string)($config['school_phone']??'GRC Admissions'));$address=htmlspecialchars((string)($config['school_address']??'Global Reciprocal Colleges'));$html='<h2>GRC application decision</h2><p>Dear '.$name.',</p><p>We regret to inform you that your application was not approved after review.</p><p><b>Application reference:</b> '.$reference.'</p>'.$reason.'<p>If you believe information is missing or would like clarification, please call the school at <b>'.$phone.'</b> or visit <b>'.$address.'</b>. Please bring your reference ID and supporting documents.</p><p>Thank you for your interest in Global Reciprocal Colleges.</p>';$emailSent=send_system_mail($a['email'],'GRC Application Update – Not Approved',$html);}
   else{$html='<h2>Action required for your GRC application</h2><p>Dear '.$name.',</p><p>We need additional information or corrected documents before processing your application.</p><p><b>Application reference:</b> '.$reference.'</p><p>'.nl2br(htmlspecialchars($message?:'Please contact GRC Admissions for the required corrections.')).'</p>';$emailSent=send_system_mail($a['email'],'Action Required for Your GRC Application',$html);}
  }
  audit('application.'.$status,'applications',$id,['email_sent'=>$emailSent??false]);respond(['success'=>true,'data'=>['email_sent'=>$emailSent??false]]);
 }
 if($action==='ticket_create'&&$method==='POST'){$u=require_permission('tickets.create');csrf_check();$n='HD-'.date('ymd').'-'.strtoupper(bin2hex(random_bytes(2)));$pdo=db();$pdo->beginTransaction();$pdo->prepare("INSERT INTO tickets(ticket_number,student_user_id,category,subject,status) VALUES(?,?,?,?,'open')")->execute([$n,$u['id'],$json['category']??'General',trim($json['subject']??'')]);$id=(int)$pdo->lastInsertId();$pdo->prepare('INSERT INTO ticket_messages(ticket_id,sender_user_id,message) VALUES(?,?,?)')->execute([$id,$u['id'],trim($json['message']??'')]);$pdo->commit();respond(['success'=>true,'data'=>['ticket_number'=>$n]]);}
 if($action==='ticket'){$u=require_permission('tickets.view');$id=(int)($_GET['id']??0);$q=db()->prepare('SELECT * FROM tickets WHERE id=?');$q->execute([$id]);$t=$q->fetch();if(!$t||($u['role_name']==='Student'&&(int)$t['student_user_id']!==$u['id']))respond(['success'=>false,'error'=>'Ticket not found.'],404);$q=db()->prepare('SELECT tm.*,u.email sender_email FROM ticket_messages tm JOIN users u ON u.id=tm.sender_user_id WHERE tm.ticket_id=? ORDER BY tm.created_at');$q->execute([$id]);respond(['success'=>true,'data'=>['ticket'=>$t,'messages'=>$q->fetchAll()]]);}
 if($action==='ticket_reply'&&$method==='POST'){$u=require_auth();csrf_check();$id=(int)$json['id'];$q=db()->prepare('SELECT * FROM tickets WHERE id=?');$q->execute([$id]);$t=$q->fetch();if(!$t||($u['role_name']==='Student'?(int)$t['student_user_id']!==$u['id']:!can('tickets.manage')))respond(['success'=>false,'error'=>'Permission denied.'],403);db()->prepare('INSERT INTO ticket_messages(ticket_id,sender_user_id,message) VALUES(?,?,?)')->execute([$id,$u['id'],trim($json['message']??'')]);if($u['role_name']!=='Student')db()->prepare("UPDATE tickets SET status='in_progress',assigned_to=? WHERE id=?")->execute([$u['id'],$id]);respond(['success'=>true]);}
 if($action==='announcement_create'&&$method==='POST'){$u=require_permission('announcements.manage');csrf_check();db()->prepare('INSERT INTO announcements(title,body,audience,is_published,published_by,published_at) VALUES(?,?,?,1,?,NOW())')->execute([$json['title'],$json['body'],$json['audience']??'all',$u['id']]);respond(['success'=>true]);}
 respond(['success'=>false,'error'=>'Route not found.'],404);
 // Roll back incomplete database work and send consistent errors that the frontend can display.
 } catch(PDOException $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();error_log($e->__toString());$mysqlCode=(int)($e->errorInfo[1]??0);if($mysqlCode===1062)respond(['success'=>false,'error'=>'A record with the same email, username, student number, or reference already exists.'],409);if($mysqlCode===1452)respond(['success'=>false,'error'=>'A required related record is missing. Check the selected program, role, or section.'],422);respond(['success'=>false,'error'=>'The database could not complete this request. Check that the latest database schema is imported.'],500);}catch(Throwable $e){if(isset($pdo)&&$pdo->inTransaction())$pdo->rollBack();error_log($e->__toString());respond(['success'=>false,'error'=>'The server could not complete this request: '.$e->getMessage()],500);}
// Small data helpers used by the student and admin portal routes above.
function applications():array{return db()->query("SELECT a.id,a.reference_id,CONCAT(a.first_name,' ',a.last_name) name,a.email,a.status,p.program_code FROM applications a LEFT JOIN programs p ON p.id=a.program_id WHERE a.status!='draft' ORDER BY a.updated_at DESC LIMIT 100")->fetchAll();}
function student(int $uid){$q=db()->prepare("SELECT sp.*,a.first_name,a.middle_name,a.last_name,a.email,a.birth_date,a.contact_number,a.present_address,p.program_code,p.program_name,se.section_name,se.year_level,se.school_year,se.semester,'enrolled' enrollment_status FROM student_profiles sp JOIN applications a ON a.id=sp.application_id JOIN programs p ON p.id=sp.program_id LEFT JOIN sections se ON se.id=sp.section_id WHERE sp.user_id=?");$q->execute([$uid]);return $q->fetch();}
function schedule(int $section,?string $day=null):array{$sql="SELECT su.subject_code,su.subject_name,su.units,sc.day_of_week,TIME_FORMAT(sc.start_time,'%h:%i %p') start_time,TIME_FORMAT(sc.end_time,'%h:%i %p') end_time,sc.room,sc.instructor FROM class_schedules sc JOIN subjects su ON su.id=sc.subject_id WHERE sc.section_id=?".($day?' AND sc.day_of_week=?':'').' ORDER BY sc.start_time';$q=db()->prepare($sql);$q->execute($day?[$section,$day]:[$section]);return $q->fetchAll();}
function balance(int $student):array{$q=db()->prepare('SELECT id,description,amount,amount_paid,due_date,school_year,semester,CASE WHEN amount_paid>=amount THEN \'Paid\' WHEN amount_paid>0 THEN \'Partial\' ELSE \'Unpaid\' END payment_status FROM assessments WHERE student_profile_id=? ORDER BY due_date,created_at');$q->execute([$student]);$items=$q->fetchAll();$a=0.0;$p=0.0;foreach($items as $item){$a+=(float)$item['amount'];$p+=(float)$item['amount_paid'];}return ['assessment'=>$a,'paid'=>$p,'balance'=>$a-$p,'items'=>$items,'online_payment_enabled'=>false];}
